# Generated by Django 3.2.8 on 2021-12-26 07:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Model_name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Add_Process_or_Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Process_or_function_name', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fmea_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('Potential_Failure_Mode', models.CharField(max_length=256)),
                ('Potential_Effects_of_Failure', models.CharField(max_length=256)),
                ('Sev', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], help_text='[No effect=1] [Appearance/Noise rarely noticed by customer=2] [Appearance/Noise noticed by customer=3] [Appearance/Noise noticed by most of customer=3] [Vehicle,convenience operable,Low performance=5] [Reduction in convenience and comfort function=6][Fit-issue,Reduction in primary function=7][vehicle not operate=8][Affect safety,Govt Regul NC,with warning=9][Affect safety,Govt Reg NC,without warning=10]')),
                ('Class', models.CharField(blank=True, max_length=10, null=True)),
                ('Potential_causes_or_Mechanisms_of_Failure', models.CharField(max_length=256)),
                ('Occ', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], help_text='[No failure=1]   [1 in 10,00,000 =2] [1 in 100000=3] [1 in 10000=4], [1 in 2000=5] [1 in 500=5] [1 in 100=7] [1 in 50 = 8] [1 in 20=9] [1 in 10=10]')),
                ('Current_Process_Control_Prevention', models.CharField(max_length=256)),
                ('Current_Process_Control_Detection', models.CharField(max_length=256)),
                ('Det', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], help_text='[Design prevention=1 [Error proof prevent Error=2][Automated controls during process=3][Automated controls after process=4][Variable gauge,setup,Buzzer alarm during process=5][Attribute gauge,Manual torque during process=6][Post process/Final inspection=7][Visual,Noise inspection post process=8],[Random_audit=9][No detection method=10]')),
                ('Recommended_Actions', models.CharField(blank=True, max_length=256, null=True)),
                ('Resp_Target_Date', models.CharField(blank=True, max_length=256, null=True)),
                ('Actions_Taken', models.CharField(blank=True, max_length=256, null=True)),
                ('Sev_Rev', models.IntegerField(blank=True, null=True)),
                ('Occ_Rev', models.IntegerField(blank=True, null=True)),
                ('Det_Rev', models.IntegerField(blank=True, null=True)),
                ('Rev_No', models.IntegerField(blank=True, null=True)),
                ('Rev_Date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('Rev_History', models.CharField(blank=True, max_length=256, null=True)),
                ('Part_Name', models.ManyToManyField(blank=True, null=True, to='Fmea.Add_Part')),
                ('Process_OR_Function', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Fmea.add_process_or_function')),
            ],
        ),
    ]
